blank_issues_enabled: false
contact_links:
    - name: âš ï¸Security Issue
      url: https://docs.sylius.com/the-book/contributing/contributing-code/security-issues
      about: If you think that you have found a security issue in Sylius, please do not use the issue tracker and do not post it publicly. Instead, all security issues must be sent to `security@sylius.com`.
    - name: ğŸ™‹ğŸ¼Support Question
      url: https://sylius.com/support/
      about: GitHub issues are just for reporting Sylius bugs and suggesting new features. If you have questions about using Sylius or third-party bundles, feel free to check out our support options in `https://sylius.com/support`
    - name: ğŸ‡ºğŸ‡¸Translations
      url: https://translate.sylius.com/
      about: See `https://translate.sylius.com/` to add or fix Sylius translations.
