# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_api:
    resource: .
    type: api_platform
    prefix: /

sylius_api_admin_statistics:
    path: /admin/statistics
    methods: ['GET']
    defaults:
        _controller: sylius_api.controller.get_statistics
